### ISSUE TITLE
Set defaults masked values that can be can be opt out

### ISSUE THREAD

**Issue by umbobabo** [Financial-Times/n-mask-logger#25]
I see the risk that [we can miss some fields](https://github.com/Financial-Times/next-subscribe/pull/375/files) or a change in the data model could introduce fields that are then automatically logged.

I suggest that we add a set of defaults value that could potentially be opt-out to try to mitigate common cases of PII.

Let say our default fields are:
```js
const disallowedList = [
	'email',
	'password',
	'name', <<< This should match firstName and LastName
	'phone', <<< Should match telephone too
	'postcode'
]
// If I initiate like...

const _logger = new MaskLogger(['myCustomField']);

// Then it will use as filters all the disallowedList + myCustomField.
// If I want to opt-opt I can add explicit some allowed value maybe like this...
const _logger = new MaskLogger(['myCustomField'],['phone', 'postcode']);
// This will log phone and postcode

**Comment by remybach** [comment]
Sounds like a good idea to me 👍

**Comment by CyntiBinti** [comment]
Closing as archiving this repo
